# Generated by Django 2.2.9 on 2020-08-21 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='NAME')),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='TIME')),
                ('rating', models.IntegerField(blank=True, default='라이프 점수를 기록해주세요', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='SCORE')),
                ('category', models.CharField(blank=True, choices=[('친구/가족과의 시간', '친구/가족과의 시간'), ('자기계발', '자기계발'), ('운동', '운동'), ('취미생활', '취미생활'), ('여가생활', '여가생활'), ('여행', '여행'), ('일', '일'), ('기타', '기타')], default='친구/가족과의 시간', max_length=15, verbose_name='TYPE')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='create_profile.Profile')),
            ],
        ),
    ]
