# Generated by Django 2.2.9 on 2020-08-10 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15, verbose_name='닉네임')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='create_profile/%Y/%m/%d', verbose_name='프로필사진')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('job', models.CharField(blank=True, max_length=20, verbose_name='직업')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='소개')),
                ('goal_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
