# Generated by Django 2.2.9 on 2020-08-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='photo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_post', to='create_profile.Profile'),
        ),
    ]
