# Generated by Django 2.2.9 on 2020-08-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200818_0410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoComment',
        ),
    ]
