# Generated by Django 2.2.9 on 2020-08-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_delete_photocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Like', to='create_profile.Profile'),
        ),
    ]
