# Generated by Django 2.2.9 on 2020-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_cruduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='age',
        ),
    ]
